/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DDR } from "./DDR";
export type { Patients } from "./Patients";
export type { Pharmacy } from "./Pharmacy";
export type { Prescription } from "./Prescription";
export type { HealthRecords } from "./HealthRecords";
