/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAuthenticator,
  IAuthenticatorInterface,
} from "../../../contracts/interface/IAuthenticator";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "checkAuth",
    outputs: [
      {
        internalType: "enum AuthType",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IAuthenticator__factory {
  static readonly abi = _abi;
  static createInterface(): IAuthenticatorInterface {
    return new utils.Interface(_abi) as IAuthenticatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAuthenticator {
    return new Contract(address, _abi, signerOrProvider) as IAuthenticator;
  }
}
