/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPrescription,
  IPrescriptionInterface,
} from "../../../contracts/interface/IPrescription";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "prescriptionId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "discloseApproval",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "prescriptionId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "getDiscloseApproval",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getHealthRecordAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "setHealthRecordAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "PrescriptionIds",
        type: "uint256[]",
      },
      {
        internalType: "address",
        name: "senderAddress",
        type: "address",
      },
    ],
    name: "setLockPrescription",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPrescription__factory {
  static readonly abi = _abi;
  static createInterface(): IPrescriptionInterface {
    return new utils.Interface(_abi) as IPrescriptionInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPrescription {
    return new Contract(address, _abi, signerOrProvider) as IPrescription;
  }
}
