/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Prescription__factory } from "./Prescription__factory";
export { HealthRecords__factory } from "./HealthRecords__factory";
