/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DDR__factory } from "./DDR__factory";
export { Patients__factory } from "./Patients__factory";
export { Pharmacy__factory } from "./Pharmacy__factory";
export { Prescription__factory } from "./Prescription__factory";
export { HealthRecords__factory } from "./HealthRecords__factory";
