/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAuthenticator } from "./IAuthenticator";
export type { IDDR } from "./IDDR";
export type { IPrescription } from "./IPrescription";
