/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IPrescriptionInterface extends utils.Interface {
  functions: {
    "discloseApproval(uint256,address)": FunctionFragment;
    "getDiscloseApproval(uint256,address)": FunctionFragment;
    "getHashValue(uint256)": FunctionFragment;
    "getHealthRecordAddress()": FunctionFragment;
    "setHealthRecordAddress(address)": FunctionFragment;
    "setLockPrescription(uint256[],address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "discloseApproval"
      | "getDiscloseApproval"
      | "getHashValue"
      | "getHealthRecordAddress"
      | "setHealthRecordAddress"
      | "setLockPrescription"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "discloseApproval",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getDiscloseApproval",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getHashValue",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getHealthRecordAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setHealthRecordAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setLockPrescription",
    values: [PromiseOrValue<BigNumberish>[], PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "discloseApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDiscloseApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHashValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHealthRecordAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHealthRecordAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLockPrescription",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IPrescription extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPrescriptionInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    discloseApproval(
      prescriptionId: PromiseOrValue<BigNumberish>,
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getDiscloseApproval(
      prescriptionId: PromiseOrValue<BigNumberish>,
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getHashValue(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getHealthRecordAddress(overrides?: CallOverrides): Promise<[string]>;

    setHealthRecordAddress(
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setLockPrescription(
      PrescriptionIds: PromiseOrValue<BigNumberish>[],
      senderAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  discloseApproval(
    prescriptionId: PromiseOrValue<BigNumberish>,
    _address: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getDiscloseApproval(
    prescriptionId: PromiseOrValue<BigNumberish>,
    _address: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getHashValue(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getHealthRecordAddress(overrides?: CallOverrides): Promise<string>;

  setHealthRecordAddress(
    _address: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setLockPrescription(
    PrescriptionIds: PromiseOrValue<BigNumberish>[],
    senderAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    discloseApproval(
      prescriptionId: PromiseOrValue<BigNumberish>,
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getDiscloseApproval(
      prescriptionId: PromiseOrValue<BigNumberish>,
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getHashValue(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getHealthRecordAddress(overrides?: CallOverrides): Promise<string>;

    setHealthRecordAddress(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setLockPrescription(
      PrescriptionIds: PromiseOrValue<BigNumberish>[],
      senderAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    discloseApproval(
      prescriptionId: PromiseOrValue<BigNumberish>,
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getDiscloseApproval(
      prescriptionId: PromiseOrValue<BigNumberish>,
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getHashValue(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getHealthRecordAddress(overrides?: CallOverrides): Promise<BigNumber>;

    setHealthRecordAddress(
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setLockPrescription(
      PrescriptionIds: PromiseOrValue<BigNumberish>[],
      senderAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    discloseApproval(
      prescriptionId: PromiseOrValue<BigNumberish>,
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getDiscloseApproval(
      prescriptionId: PromiseOrValue<BigNumberish>,
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getHashValue(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getHealthRecordAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setHealthRecordAddress(
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setLockPrescription(
      PrescriptionIds: PromiseOrValue<BigNumberish>[],
      senderAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
