/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as authenticatorSol from "./Authenticator.sol";
export type { authenticatorSol };
export type { ERC721Base } from "./ERC721Base";
